{% set name = "sphinx-tabs" %}
{% set version = "3.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d10dd7fb2700329b8e5948ab9f8e3ef54fff30f79d2e42cfd1b0089ae26e8c5e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pygments
    - python >=3.6
    - sphinx >=2,<5
    - pygments
    - docutils >=0.16.0

test:
  imports:
    - sphinx_tabs

about:
  home: https://github.com/executablebooks/sphinx-tabs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tabbed views for Sphinx
  doc_url: https://sphinx-tabs.readthedocs.io/

extra:
  recipe-maintainers:
    - chrisjsewell
    - danielfrg
